### ISSUE TITLE
when I enter this task, my screen turns white and everything disappears

### ISSUE THREAD

**Issue by SadBatya** [Hopding/js-visualizer-9000-client#52]
let promiseTwo = new Promise((resolve, reject) => {
  resolve("a");
});
promiseTwo
  .then((res) => {
      return res + "b";
  })
  .then((res) => {
      return res + "с";
  })
  .finally((res) => {
      return res + "!!!!!!!";
  })
  .catch((res) => {
      return res + "d";
  })
  .then((res) => {
      console.log(res);
  });

**Comment by SadBatya** [comment]
and in console i have this error

console.js:288 DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at https://www.jsv9000.app/static/js/main.61ee41a9.chunk.js:1:16875
    at Xo (https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:671404)
    at ja (https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:680292)
    at bs (https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:719153)
    at bl (https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:710558)
    at vl (https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:710483)
    at ul (https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:707485)
    at https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:658675
    at t.unstable_runWithPriority (https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:734345)
    at Hi (https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:658385)

**Comment by SadBatya** [comment]
everything works with other tasks

**Comment by gorbatkoff** [comment]
same problem

**Comment by DularBaxture** [comment]
as the

> and in console i have this error
> 
> console.js:288 DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range. at https://www.jsv9000.app/static/js/main.61ee41a9.chunk.js:1:16875 at Xo (https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:671404) at ja (https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:680292) at bs (https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:719153) at bl (https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:710558) at vl (https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:710483) at ul (https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:707485) at https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:658675 at t.unstable_runWithPriority (https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:734345) at Hi (https://www.jsv9000.app/static/js/2.7f47a97c.chunk.js:1:658385)

Hii @SadBatya  , As this error suggest your code have character outside the Latin Range .
 in code [return res + "с";] the character c is Cyrillic letter .

try below corrected code.
`
let promiseTwo = new Promise((resolve, reject) => {
	resolve('a');
});
promiseTwo
	.then((res) => {
		return res + 'b';
	})
	.then((res) => {
		return res + 'c';
	})
	.finally((res) => {
		return res + '!!!!!!!';
	})
	.catch((res) => {
		return res + 'd';
	})
	.then((res) => {
		console.log(res);
	});
`
